// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Client from "react-dom/client";

function ReactExample$Button(Props) {
  var variantOpt = Props.variant;
  var children = Props.children;
  var variant = variantOpt !== undefined ? variantOpt : /* Primary */0;
  var className = variant ? "btn btn-link" : "btn btn-primary";
  return React.createElement("button", {
              className: className
            }, children);
}

Client.createRoot(document.body).render(React.createElement("div", undefined, React.createElement(ReactExample$Button, {
              children: "Continue"
            }), React.createElement(ReactExample$Button, {
              variant: /* Link */1,
              children: "cancel"
            })));

export {
  
}
/*  Not a pure module */
